apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-deployment
  labels:
    app: movies-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movies-api
  template:
    metadata:
      name: movies-pod
      labels:
        app: movies-api
    spec:
      containers:
      - name: movies-api
        image: movies-api
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 8081
        env:
        - name: spring.data.mongodb.username
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: spring.data.mongodb.password
          valueFrom: 
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
        - name: spring.data.mongodb.host
          valueFrom: 
            configMapKeyRef:
              name: mongodb-configmap
              key: database_url
---
apiVersion: v1
kind: Service
metadata:
  name: movies-service
spec:
  selector:
    app: movies-api
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30000
